#!/bin/bash

# 테스트 디렉토리 생성
mkdir -p test_images/folder1/folder2/sequence
mkdir -p test_images/folder1/folder3/sequence
mkdir -p test_images/folder2/folder4/sequence

# 실행 권한 부여
chmod +x gif_maker.py batch_gif_maker.py install_pip.sh install_without_pip.sh setup_venv.sh

echo "GIF 메이커 사용 예시:"
echo ""
echo "설치 방법:"
echo "1. 가상 환경 설정 (권장):"
echo "   ./setup_venv.sh"
echo "   source venv/bin/activate"
echo ""
echo "2. pip 사용:"
echo "   pip install -r requirements.txt"
echo ""
echo "3. pip가 없는 경우:"
echo "   ./install_pip.sh"
echo "   python3 -m pip install -r requirements.txt"
echo ""
echo "4. Homebrew 사용:"
echo "   ./install_without_pip.sh"
echo ""
echo "사용 예시:"
echo ""
echo "1. 단일 폴더 처리:"
echo "   # 일반 사용:"
echo "   python3 gif_maker.py ./test_images/folder1/folder2/sequence output.gif"
echo "   # 가상 환경 사용 시:"
echo "   python gif_maker.py ./test_images/folder1/folder2/sequence output.gif"
echo ""
echo "2. 프레임 간격 및 크기 조정:"
echo "   # 일반 사용:"
echo "   python3 gif_maker.py ./test_images/folder1/folder2/sequence output.gif -d 200 -r 800x600"
echo "   # 가상 환경 사용 시:"
echo "   python gif_maker.py ./test_images/folder1/folder2/sequence output.gif -d 200 -r 800x600"
echo ""
echo "3. 반복 횟수 설정 (1회만 재생):"
echo "   # 일반 사용:"
echo "   python3 gif_maker.py ./test_images/folder1/folder2/sequence output.gif -l 1"
echo "   # 가상 환경 사용 시:"
echo "   python gif_maker.py ./test_images/folder1/folder2/sequence output.gif -l 1"
echo ""
echo "4. 배치 처리 (모든 sequence 폴더 처리):"
echo "   # 일반 사용:"
echo "   python3 batch_gif_maker.py test_images"
echo "   # 가상 환경 사용 시:"
echo "   python batch_gif_maker.py test_images"
echo ""
echo "5. 배치 처리 (옵션 적용):"
echo "   # 일반 사용:"
echo "   python3 batch_gif_maker.py test_images -d 200 -r 800x600"
echo "   # 가상 환경 사용 시:"
echo "   python batch_gif_maker.py test_images -d 200 -r 800x600"
echo ""
echo "테스트 이미지를 ./test_images 하위 폴더의 sequence 폴더에 넣은 후 위 명령어를 실행해보세요."
echo "예: test_images/folder1/folder2/sequence/*.jpg -> test_images/folder1/folder2.gif" 